extends CardEffectGeneric
## Auto-generated by tools/generate_card_effect_scripts.py — re-run after catalog sync.
## Safe to edit: add gameplay hooks; keep snapshots or refresh from catalog as you prefer.
##
## Card: support_cards / PROTOMBSSUPP060
## Name: Social Media Campaign

## Snapshot from catalog at generation time (used when live row omits these fields, e.g. thin overlays).
const _SNAPSHOT_ABILITY := "\u2014"
const _SNAPSHOT_EFFECT := "Both Players add their staff cost to their value"


func ability_text() -> String:
	var live := CardRowText.ability_from_row(row)
	if not live.is_empty() and live != "—":
		return live
	return _SNAPSHOT_ABILITY if not _SNAPSHOT_ABILITY.is_empty() else "—"


func effect_text() -> String:
	var live := CardRowText.effect_from_row(row)
	if not live.is_empty() and live != "—":
		return live
	return _SNAPSHOT_EFFECT if not _SNAPSHOT_EFFECT.is_empty() else "—"


## Optional CPU-match banner on the hand card; return text to show, or "" for none.

func on_faceoff_reveal(ctx: MatchEffectContext, owner: int, slot: int) -> void:
	CardEffectImpl.on_reveal(self, ctx, owner, slot)


func on_faceoff_before_score(ctx: MatchEffectContext, owner: int) -> void:
	CardEffectImpl.before_score(self, ctx, owner)


func modify_meal_value(ctx: MatchEffectContext, owner: int, meal_row: Dictionary, base_value: int) -> int:
	return CardEffectImpl.modify_meal(self, ctx, owner, meal_row, base_value)


func modify_total_score(ctx: MatchEffectContext, owner: int, base_total: int) -> int:
	return CardEffectImpl.modify_total(self, ctx, owner, base_total)


func on_round_end(ctx: MatchEffectContext, owner: int) -> void:
	CardEffectImpl.on_round_end(self, ctx, owner)


func cpu_match_hook_log() -> String:
	var hook := CardEffectImpl.cpu_hook(self)
	if not hook.is_empty():
		return hook
	return ""
