#!/usr/bin/env python3
"""
Emit one GDScript per catalog row that has non-empty Effect text (matches CardRowText.effect_from_row).

Reads NSD/Game/data/catalog_cache.json (sync from launcher). Playable Supabase tables only;
the aggregate `cards` table is skipped (game uses typed tables in hand/deck).

Each script embeds a JSON-escaped snapshot of catalog ability/effect plus overrides so the file
is not an empty stub (live row still wins when fields are present).

Usage (from repo root):
  python3 tools/generate_card_effect_scripts.py
  python3 tools/generate_card_effect_scripts.py --catalog /path/to/catalog_cache.json
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

PLAYABLE_TABLES = frozenset(
    {
        "chef_cards",
        "restaurant_cards",
        "staff_cards",
        "meal_cards",
        "event_cards",
        "support_cards",
    }
)

DASH = "\u2014"  # matches CardRowText empty sentinel


def row_id(row: dict) -> str:
    keys = [
        "id",
        "uuid",
        "UUID",
        "Id",
        "ID",
        "code",
        "Code",
        "CODE",
        "card_id",
        "cardId",
        "CardId",
        "CARD_ID",
        "chef_id",
        "ChefId",
        "CHEF_ID",
    ]
    for k in keys:
        if k not in row or row[k] is None:
            continue
        s = str(row[k]).strip()
        if s:
            return s
    return ""


def ability_from_row(row: dict) -> str:
    for k in ["ability_description", "ability", "Ability", "ability_text", "AbilityText"]:
        if k not in row:
            continue
        s = str(row[k]).strip()
        if s:
            return s
    return DASH


def effect_from_row(row: dict) -> str:
    for k in ["effect_description", "effect", "Effect", "EffectText", "effect_text"]:
        if k not in row:
            continue
        s = str(row[k]).strip()
        if s:
            return s
    if "description" in row:
        d = str(row["description"]).strip()
        if d and len(d) < 220:
            return d
    return DASH


def card_title(row: dict, table: str, code: str) -> str:
    if table == "chef_cards":
        for k in ("chef_name", "ChefName", "name", "Name"):
            if k in row and row[k] is not None:
                s = str(row[k]).strip()
                if s:
                    return s
    for k in ("name", "Name"):
        if k in row and row[k] is not None:
            s = str(row[k]).strip()
            if s:
                return s
    return code


def render_gd(table: str, code: str, row: dict) -> str:
    ab = ability_from_row(row)
    ef = effect_from_row(row)
    title = " ".join(str(card_title(row, table, code)).splitlines()).strip()[:400]
    ab_lit = json.dumps(ab)
    ef_lit = json.dumps(ef)
    return f"""extends CardEffectGeneric
## Auto-generated by tools/generate_card_effect_scripts.py — re-run after catalog sync.
## Safe to edit: add gameplay hooks; keep snapshots or refresh from catalog as you prefer.
##
## Card: {table} / {code}
## Name: {title}

## Snapshot from catalog at generation time (used when live row omits these fields, e.g. thin overlays).
const _SNAPSHOT_ABILITY := {ab_lit}
const _SNAPSHOT_EFFECT := {ef_lit}


func ability_text() -> String:
	var live := CardRowText.ability_from_row(row)
	if not live.is_empty() and live != "{DASH}":
		return live
	return _SNAPSHOT_ABILITY if not _SNAPSHOT_ABILITY.is_empty() else "{DASH}"


func effect_text() -> String:
	var live := CardRowText.effect_from_row(row)
	if not live.is_empty() and live != "{DASH}":
		return live
	return _SNAPSHOT_EFFECT if not _SNAPSHOT_EFFECT.is_empty() else "{DASH}"


## Optional CPU-match banner on the hand card; return text to show, or \"\" for none.
func cpu_match_hook_log() -> String:
	var hook := CardEffectImpl.cpu_hook(self)
	if not hook.is_empty():
		return hook
	return ""


func on_faceoff_reveal(ctx: MatchEffectContext, owner: int, slot: int) -> void:
	CardEffectImpl.on_reveal(self, ctx, owner, slot)


func on_faceoff_before_score(ctx: MatchEffectContext, owner: int) -> void:
	CardEffectImpl.before_score(self, ctx, owner)


func modify_meal_value(ctx: MatchEffectContext, owner: int, meal_row: Dictionary, base_value: int) -> int:
	return CardEffectImpl.modify_meal(self, ctx, owner, meal_row, base_value)


func modify_total_score(ctx: MatchEffectContext, owner: int, base_total: int) -> int:
	return CardEffectImpl.modify_total(self, ctx, owner, base_total)


func on_round_end(ctx: MatchEffectContext, owner: int) -> void:
	CardEffectImpl.on_round_end(self, ctx, owner)
"""


def safe_filename_part(s: str) -> str:
    out = re.sub(r"[^a-zA-Z0-9_]+", "_", s)
    return out.strip("_") or "unknown"


def main() -> int:
    root = Path(__file__).resolve().parents[1]
    default_catalog = root / "NSD" / "Game" / "data" / "catalog_cache.json"
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", type=Path, default=default_catalog)
    ap.add_argument(
        "--out-dir",
        type=Path,
        default=root / "NSD" / "Game" / "scripts" / "card_effects" / "catalog_generated",
    )
    args = ap.parse_args()
    cat_path: Path = args.catalog
    out_dir: Path = args.out_dir
    if not cat_path.is_file():
        print(f"error: catalog not found: {cat_path}", file=sys.stderr)
        return 1
    data = json.loads(cat_path.read_text(encoding="utf-8"))
    tables = data.get("tables")
    if not isinstance(tables, dict):
        print("error: catalog missing tables object", file=sys.stderr)
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)
    wanted: set[str] = set()
    written = 0
    for table, rows in tables.items():
        if table not in PLAYABLE_TABLES or not isinstance(rows, list):
            continue
        for row in rows:
            if not isinstance(row, dict):
                continue
            if effect_from_row(row) == DASH:
                continue
            rid = row_id(row)
            if not rid:
                continue
            fname = f"effect_{safe_filename_part(table)}_{safe_filename_part(rid)}.gd"
            path = out_dir / fname
            path.write_text(render_gd(table, rid, row), encoding="utf-8")
            wanted.add(fname)
            written += 1

    removed = 0
    for p in out_dir.glob("effect_*.gd"):
        if p.name not in wanted:
            p.unlink()
            removed += 1

    print(f"wrote {written} scripts under {out_dir.relative_to(root)}")
    if removed:
        print(f"removed {removed} stale generated scripts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
